from sets import Set


def flipSet(wordSet):
	newSet = []
	for i in wordSet:
		newSet.append([i[1],i[0]])
	print newSet
	return newSet

if False:
	wordSet = [['AAAAAGAAAAA', 29], ['AAACAGAAAAA', 29], ['AAACAAAAAAA', 29], ['AAAAAAAAAAA', 29], ['AAACCTGACAC', 37], ['AAAAAGCAACA', 146], ['ACACAACAACA', 12], ['ACAAAACAACA', 12], ['ACAAAAACGAA', 46], ['ACAAAAGCGAA', 46], ['TAAAAAAAAAC', 30], ['AAACGTGACAC', 37], ['AAAACCAGACA', 36], ['AAACCTGACAA', 37], ['ACACAACAAAA', 12], ['AACCTGATACA', 38], ['ATACAAAAAAA', 29], ['AACCTAACACA', 38], ['ATAAAGAAAAA', 29], ['AATAAAAAGCA', 143], ['AAACCAGATAC', 37], ['ATACAGAAAAA', 29], ['AAACCGGACAC', 37], ['AAATACCAGTA', 124], ['AACAACCAAAA', 101], ['AATCAAAAGCA', 143], ['TAAAAGCAACA', 146], ['AAAAACCAAAA', 101], ['AAAAGCAACCC', 147], ['AAACCTCACAC', 37], ['AAACAGACAAA', 29], ['AACAAGCAAAA', 114], ['AAAAAAGAAAC', 30], ['AAAAAGAGAAA', 29], ['ACAGAAGCGAA', 46], ['AAACAGATAAA', 29], ['AACCAAACACA', 38], ['AGCCAAAAAAA', 69], ['AATCAGAAAAA', 29], ['AACTAACACAG', 60], ['AAAACGAAAAA', 29], ['ACAAAACTACA', 12], ['AAAAAAACGAA', 46], ['ACAAAACAAAA', 12], ['AAAAATAAAAA', 29], ['ATAAGAAAAAC', 30], ['AAACGTGACAA', 37], ['ACCCAAACCAA', 105], ['AAAACAAACAC', 74], ['AAACGAGACAC', 37], ['AAACAGAGAAA', 29], ['AAAAACAACAC', 147], ['AAACCAGACAC', 37], ['AAAAACAAAAA', 29], ['ACACAAAAACG', 44], ['AAACCAAAAAA', 29], ['AAACGTGATAC', 37], ['ATACACAAACG', 44], ['ATAATAAACCA', 159], ['AACAAACAAAC', 30], ['AACAAGCATAA', 114], ['ATAATCAACCA', 159], ['TAAAAAGAAAC', 145], ['ACCAACAGGCA', 111], ['AAACCGGACAA', 37], ['CAAAAGCAACA', 146], ['CATAAAATACC', 120], ['AAACCGAAAAA', 29], ['AAACGAGATAC', 37], ['ATATTAAACCA', 159], ['TAGAAAGCAAC', 145], ['AAGAAAAACCT', 32], ['AAAAAAATAAA', 29], ['ACAATAAACCA', 159], ['AAAAAGCAATA', 146], ['AGCAAAAAACA', 69], ['AAACGGCACAC', 37], ['AAACCAGATAA', 37], ['ACCAACGGGCA', 111], ['AACCCAAAACA', 104], ['ACAAAGAAACG', 44], ['AAACCACACAC', 37], ['AAAAAAAACAC', 74], ['AACAAAAACCA', 104], ['AAAAAACAACA', 12], ['ACCAGAAAAAC', 30], ['AAATCTGACAC', 37], ['AATCAAAAAAA', 29], ['ACAAATAAACC', 31], ['AACAAAGAAAC', 30], ['ACACAACTACA', 12], ['AAAAGCAACTC', 147], ['AACGGGACACA', 38], ['AAAGACCAGTA', 124], ['AGATAAAAACA', 69], ['AAACCGGATAC', 37], ['GCAAAAAAGAC', 119], ['CAACAACAAAA', 100], ['AAAAAGAAACA', 146], ['AAAAAACACAC', 74]]
	newWordSet = []

	for i in wordSet:
		newWordSet.append([i[1],i[0]])

	print newWordSet

if True:
	wordSet = [[29, 'AAACAGAAAAA'], [30, 'AAAAGAAAAAC'], [29, 'AAACAAAAAAA'], [29, 'AAAAAAAAAAA'], [37, 'AAACCTGACAC'], [146, 'AAAAAGCAACA'], [12, 'ACACAACAACA'], [12, 'ACAAAACAACA'], [37, 'AAACCAGACAC'], [12, 'ACAAAACAAAA'], [44, 'ACACAAAAACG'], [12, 'ACACAACAAAA'], [37, 'AAACCTGATAC'], [46, 'ACAAAAGCGAA'], [30, 'TACAAAAAAAC'], [146, 'AAAAAGCAACC'], [37, 'AAACCGGACAC'], [29, 'ATAAAGAAAAA'], [29, 'ATAAAAAAAAA'], [37, 'AAACGTGACAC'], [37, 'AAACCAGATAC'], [29, 'ATACAGAAAAA'], [146, 'CAAAAGCAACA'], [37, 'AAACGAGACAC'], [37, 'AAACGTGATAC'], [37, 'AAACCTCACAC'], [37, 'AAACCTGACAA'], [29, 'AAAAAGATAAA'], [101, 'AAAAACCAAAA'], [29, 'AAAAAGAAAAA'], [29, 'AAACAAATAAA'], [37, 'AAACCTAACAC'], [44, 'ATACAAAAACG'], [120, 'CATAAAATACC'], [29, 'AAACAGATAAA'], [74, 'AAAAAAAACAC'], [37, 'AAACCAGACAA'], [119, 'GCAAAAAATAC'], [37, 'AAACCTGATAA'], [143, 'AATAAAAAGCA'], [12, 'AAAAAACAACA'], [119, 'GCATAAAAGAC'], [12, 'AAACAACAACA'], [159, 'ATAATAAACCA'], [69, 'AGCTAAAAAAA'], [69, 'AGCAAAAAAAA'], [159, 'ATAATCAACCA'], [37, 'AAACCGGATAC'], [37, 'AAACCTCATAC'], [74, 'AAAACAAACAC'], [146, 'AAAAACCAACA'], [12, 'AGACAACAACA'], [29, 'AAACACAAAAA'], [29, 'AAAAAGAGAAA'], [29, 'AAAAAAAGAAA'], [105, 'ACCAAAACCAA'], [30, 'AAAAAATAAAC'], [146, 'AAAAAGAAACA'], [146, 'CAAAAGCAACC'], [69, 'AGCAGAAAAAA'], [37, 'AAACCGGACAA'], [100, 'CAAAAACCCAA'], [29, 'AAACAAAGAAA'], [29, 'AAACATAAAAA'], [29, 'AATCAGAAAAA'], [120, 'CAAAAAAGACC'], [29, 'AAAAACAAAAA'], [46, 'AAAAAAACGAA'], [37, 'AAACGGGACAC'], [29, 'AAACAGAGAAA'], [29, 'AATCAAAAAAA'], [159, 'ACAATAAACCA'], [38, 'AACCACACACA'], [29, 'AAACCGAAAAA'], [74, 'AAAAAACACAC'], [12, 'AGAAAACAAAA'], [145, 'TTAAAAGCAAC'], [12, 'AGAAAACAACA'], [29, 'AATAAGAAAAA'], [37, 'AAACCTTACAC'], [12, 'AAACAACAAAA'], [29, 'AAACAAACAAA'], [101, 'AAGAACCCAAA'], [29, 'AAACAGACAAA'], [105, 'ACCAAAACAAA'], [30, 'AACAAAAAAAC'], [29, 'CAACAGAAAAA'], [69, 'AGCAGAAAACA'], [46, 'ACAGAAACGAA'], [37, 'AAACGAGATAC'], [37, 'AAACCGAACAC'], [146, 'AGAAAGCAACA'], [37, 'AAACGTCACAC'], [146, 'AAAAAGCAACT'], [37, 'AAACCAAACAC'], [69, 'AGATGAAAAAA'], [12, 'ACAACACAACA'], [69, 'AGAAGAAAAAA'], [37, 'AAACCGCACAC'], [46, 'ACAGAAGCGAA']]
	numbers = []

	for i in wordSet:
		numbers.append(i[0])
	print numbers











if False:
	words = ['ACCAACAAGCA', 'ACCAACACGCA', 'ACCAACAGGCA', 'ACAAACAAGCA', 'ACAAACACGCA', 'ACAAACAGGCA', 'AACAACAAGCA', 'ACCAACGAGCA', 'AACAACACGCA', 'AACAACAGGCA']

	index = 111

	finalList = []

	for i in words:
		finalList.append([index,i])

	#print finalList

	wordSet = [['ACACTCCTACA', 4], ['GCCGACACAAC', 8], ['CGACACTACAA', 10], ['GATAAAACAAA', 11], ['ACAAAACAACA', 12], ['ACAAAACCAAA', 12], ['AAACAACAAAA', 12], ['ACAACACAACA', 12], ['AGAATACAACA', 12], ['ACAATACCACA', 12], ['ACACAATAACA', 12], ['ACACAACAAAA', 12], ['AAAAAACAACA', 12], ['ACAACAATCAA', 17], ['GAAACAGAAAA', 28], ['GAAAAAAAGAA', 28], ['AAACAAAAAAA', 29], ['ATACAGAAAAA', 29], ['AAAAAAAAAAA', 29], ['AAAAGAAAAAA', 29], ['AATCAGAAAAA', 29], ['AATAAAAAAAA', 29], ['AAACAAAGAAA', 29], ['AAAAAACAAAA', 29], ['AATAAGAAAAA', 29], ['ATACAAAAAAA', 29], ['AAAAAGAGAAA', 29], ['AAACAGATAAA', 29], ['AAAAGGAAAAA', 29], ['AAAAAGAAAAA', 29], ['ATACAGATAAA', 29], ['AACAACAAAAC', 30], ['AACAGAGAAAC', 30], ['AACAGAAAAAT', 30], ['ACAGAAAAACC', 31], ['ACAAATAAACC', 31], ['AAAAACCTTAC', 35], ['AAAACCAGATA', 36], ['AAACCTGACAA', 37], ['AAACGACACAC', 37], ['AAACATGACAC', 37], ['AAACCTCACAC', 37], ['AAACGTAACAC', 37], ['AAATCTGACAA', 37], ['AAACCGGATAC', 37], ['AAACGTGACAC', 37], ['AAATGAGACAC', 37], ['AAACCTGACAC', 37], ['AACCGGACACA', 38], ['AATCTCACACA', 38], ['AACGTGATAAA', 38], ['AACCTAACACA', 38], ['AACCGCACAAA', 38], ['AACCTGATACA', 38], ['AACCGTATACA', 38], ['AACCAGACACA', 38], ['ATAAAAAAACG', 44], ['ATACAGAAACG', 44], ['ATACAAAAACG', 44], ['ACAAAAAAACG', 44], ['ACACAGAAACG', 44], ['ACACAAACGAA', 46], ['ACAAAAGCAAA', 46], ['ACAAAAGCGAA', 46], ['AACCTAACTAA', 55], ['AACTCACACAG', 60], ['AAATCACACAG', 60], ['AAATAATACAG', 60], ['CATCCAGCTAA', 64], ['AGCTGAAAAAA', 69], ['AGCCGAAAACA', 69], ['AGCTGAAAACA', 69], ['AGACAAAAAAA', 69], ['AAAAAACAGAC', 74], ['AAAACAAGAAC', 96], ['AACAACCAAAA', 101], ['AAACCAAAACC', 103], ['AAACAAAACCA', 104], ['ACAAAAAACAA', 105], ['AACAACTCGCA', 111], ['ACCAACAGGCA', 111], ['AACAGGCACAA', 114], ['CAAAAAAGACC', 120], ['ATAAAATACCA', 121], ['ATAAAAGCCCA', 121], ['ACATACCAGTA', 124], ['ACTAAAAACCA', 143], ['AATAAAAAACA', 143], ['AACAAAAAGCA', 143], ['AACAAAAGCAA', 144], ['TAAAAAGCAAC', 145], ['CTAAAAGCAAC', 145], ['AAAAAGTAACA', 146], ['ATAAAGCAACA', 146], ['AAAAGCAAAAC', 147], ['AAAAGCAATAC', 147], ['ACATTAAACCA', 159], ['ATAATAAACCA', 159], ['ATATTAAACCA', 159], ['ATATTAAAACA', 159]]
	newList = []

	for i in wordSet:
		newList.append([i[1],i[0]])
	#print newList


	words = [[4, 'ACACTCCTACA'], [8, 'GCCGACACAAC'], [10, 'CGACACTACAA'], [11, 'GATAAAACAAA'], [12, 'ACAAAACAACA'], [12, 'ACAAAACCAAA'], [12, 'AAACAACAAAA'], [12, 'ACAACACAACA'], [12, 'AGAATACAACA'], [12, 'ACAATACCACA'], [12, 'ACACAATAACA'], [12, 'ACACAACAAAA'], [12, 'AAAAAACAACA'], [17, 'ACAACAATCAA'], [28, 'GAAACAGAAAA'], [28, 'GAAAAAAAGAA'], [29, 'AAACAAAAAAA'], [29, 'ATACAGAAAAA'], [29, 'AAAAAAAAAAA'], [29, 'AAAAGAAAAAA'], [29, 'AATCAGAAAAA'], [29, 'AATAAAAAAAA'], [29, 'AAACAAAGAAA'], [29, 'AAAAAACAAAA'], [29, 'AATAAGAAAAA'], [29, 'ATACAAAAAAA'], [29, 'AAAAAGAGAAA'], [29, 'AAACAGATAAA'], [29, 'AAAAGGAAAAA'], [29, 'AAAAAGAAAAA'], [29, 'ATACAGATAAA'], [30, 'AACAACAAAAC'], [30, 'AACAGAGAAAC'], [30, 'AACAGAAAAAT'], [31, 'ACAGAAAAACC'], [31, 'ACAAATAAACC'], [35, 'AAAAACCTTAC'], [36, 'AAAACCAGATA'], [37, 'AAACCTGACAA'], [37, 'AAACGACACAC'], [37, 'AAACATGACAC'], [37, 'AAACCTCACAC'], [37, 'AAACGTAACAC'], [37, 'AAATCTGACAA'], [37, 'AAACCGGATAC'], [37, 'AAACGTGACAC'], [37, 'AAATGAGACAC'], [37, 'AAACCTGACAC'], [38, 'AACCGGACACA'], [38, 'AATCTCACACA'], [38, 'AACGTGATAAA'], [38, 'AACCTAACACA'], [38, 'AACCGCACAAA'], [38, 'AACCTGATACA'], [38, 'AACCGTATACA'], [38, 'AACCAGACACA'], [44, 'ATAAAAAAACG'], [44, 'ATACAGAAACG'], [44, 'ATACAAAAACG'], [44, 'ACAAAAAAACG'], [44, 'ACACAGAAACG'], [46, 'ACACAAACGAA'], [46, 'ACAAAAGCAAA'], [46, 'ACAAAAGCGAA'], [55, 'AACCTAACTAA'], [60, 'AACTCACACAG'], [60, 'AAATCACACAG'], [60, 'AAATAATACAG'], [64, 'CATCCAGCTAA'], [69, 'AGCTGAAAAAA'], [69, 'AGCCGAAAACA'], [69, 'AGCTGAAAACA'], [69, 'AGACAAAAAAA'], [74, 'AAAAAACAGAC'], [96, 'AAAACAAGAAC'], [101, 'AACAACCAAAA'], [103, 'AAACCAAAACC'], [104, 'AAACAAAACCA'], [105, 'ACAAAAAACAA'], [111, 'AACAACTCGCA'], [111, 'ACCAACAGGCA'], [114, 'AACAGGCACAA'], [120, 'CAAAAAAGACC'], [121, 'ATAAAATACCA'], [121, 'ATAAAAGCCCA'], [124, 'ACATACCAGTA'], [143, 'ACTAAAAACCA'], [143, 'AATAAAAAACA'], [143, 'AACAAAAAGCA'], [144, 'AACAAAAGCAA'], [145, 'TAAAAAGCAAC'], [145, 'CTAAAAGCAAC'], [146, 'AAAAAGTAACA'], [146, 'ATAAAGCAACA'], [147, 'AAAAGCAAAAC'], [147, 'AAAAGCAATAC'], [159, 'ACATTAAACCA'], [159, 'ATAATAAACCA'], [159, 'ATATTAAACCA'], [159, 'ATATTAAAACA']]
	wordsCorrect = [[29, 'AAACAGAAAAA'], [29, 'AAACAAAAAAA'], [29, 'AAAAAGAAAAA'], [29, 'AAAAAAAAAAA'], [29, 'ATACAGAAAAA'], [29, 'ATACAAAAAAA'], [29, 'ATAAAGAAAAA'], [29, 'ATAAAAAAAAA'], [29, 'AAACAGATAAA'], [29, 'AAACAGAGAAA'], [29, 'AAACAAATAAA'], [29, 'AAAAAGATAAA'], [29, 'AAACAAAGAAA'], [29, 'AAAAAGAGAAA'], [29, 'AAACACAAAAA'], [29, 'AAAAAAATAAA'], [29, 'AAAAAAAGAAA'], [29, 'AAAAACAAAAA'], [29, 'AATCAGAAAAA'], [29, 'AAACATAAAAA'], [29, 'AAACAGACAAA'], [29, 'CAACAGAAAAA'], [29, 'AATCAAAAAAA'], [29, 'AATAAGAAAAA'], [29, 'AAACCGAAAAA'], [29, 'AAAAATAAAAA'], [29, 'AAACAAACAAA'],[12, 'ACAAAACAACA'], [12, 'ACACAACAACA'], [12, 'ACAAAACAAAA'], [12, 'ACACAACAAAA'], [12, 'AAAAAACAACA'], [12, 'AAACAACAACA'], [12, 'AGAAAACAACA'], [12, 'AGACAACAACA'], [12, 'AAAAAACAAAA'], [12, 'AAACAACAAAA'], [12, 'ACAATACAACA'], [12, 'ACACTACAACA'], [12, 'ATAAAACAACA'], [12, 'ATACAACAACA'], [12, 'AGAAAACAAAA'], [12, 'ACAAAACCACA'], [12, 'AGACAACAAAA'], [12, 'ACACAACCACA'], [145, 'TAAAAAGCAAC'], [145, 'AAAAAAGCAAC'], [145, 'CAAAAAGCAAC'], [145, 'TCAAAAGCAAC'], [145, 'TAAAAAACAAC'], [145, 'GAAAAAGCAAC'], [145, 'ACAAAAGCAAC'], [145, 'TAAAAACCAAC'], [145, 'TAAAAAGAAAC'], [145, 'TTAAAAGCAAC'], [145, 'CCAAAAGCAAC'], [145, 'TAAAAAGCAAT'], [145, 'TAGAAAGCAAC'], [69, 'AGCAAAAAAAA'], [69, 'AGCTAAAAAAA'], [69, 'AGAAAAAAAAA'], [69, 'AGCAGAAAAAA'], [69, 'AGATAAAAAAA'], [69, 'AGCTGAAAAAA'], [69, 'AGCAAAAAACA'], [69, 'AGCCAAAAAAA'], [69, 'AGCTAAAAACA'], [69, 'AGAAGAAAAAA'], [69, 'AGATGAAAAAA'], [69, 'AGAAAAAAACA'], [69, 'AGACAAAAAAA'], [69, 'AGCAGAAAACA'], [69, 'AGCCGAAAAAA'], [69, 'AGATAAAAACA'], [69, 'AGCTGAAAACA'], [44, 'ACACAAAAACG'], [44, 'ACACAAAAGCG'], [44, 'ATACAAAAACG'], [44, 'ATACAAAAGCG'], [44, 'ACACAGAAACG'], [44, 'ACAAAAAAACG'], [44, 'ACACAGAAGCG'], [44, 'ACACAAAAACA'], [44, 'ACAAAAAAGCG'], [44, 'ACACACAAACG'], [44, 'ACACAAAAAGG'], [44, 'ACACAAAAGCA'], [44, 'ATACAGAAACG'], [44, 'ACACACAAGCG'], [44, 'ACACAAAAAAG'], [111, 'ACCAACAAGCA'], [111, 'ACCAACACGCA'], [111, 'ACCAACAGGCA'], [111, 'ACAAACAAGCA'], [111, 'ACAAACACGCA'], [111, 'ACAAACAGGCA'], [111, 'AACAACAAGCA'], [111, 'ACCAACGAGCA'], [111, 'AACAACACGCA'], [111, 'AACAACAGGCA']]

	newWords = []

	for i in range(len(words)):
		newWords.append([wordsCorrect[i][0],words[i][1]])

	print newWords